blogTitle = "E-commerce"
authorName = "Nancy Valentina"
linkPrefix = "/gatsby-starter-blog"
bootstrap = "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
integrity = "sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7"
anon = "anonymous"
snipcartlink = "https://cdn.snipcart.com/themes/2.0/base/snipcart.min.css"
googleapis = "https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"
snipcartscript = "https://cdn.snipcart.com/scripts/2.0/snipcart.js"
snipcartdataapi = "ZDc1Yjk3NmUtYWRmNi00OWQ3LWEwMDctMGY4N2Y3MGNmYWNlNjM2MDE5NjEwNDE2OTUwMDg2"
fawesome = "http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css"
